// <auto-generated />
namespace HipsterTechnologies.API.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201503090551547_add_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
